### PR TITLE
Move stuff to api-spec folder & Add required field for psetv2 swap

### PR DESCRIPTION
**Pull request by altafan**
This moved `tdex` folder to `api-spec/protobuf` and `openapi` to `api-spec/`.

Also, this adds a new field `map<uint32, UnblindedInput> unblinded_inputs` to SwapRequest and SwapAccept messages, in order for the trader to pass unblinded input data to the provider, instead of his blinding private keys.

Please @tiero review this.

### CODE REVIEW

**Comment by tiero** [comment]
What the key of the map refers to? The input index

Wouldn't be map for script better?

**Comment by tiero** [comment]
EDIT: what if we have a `repeated` field of something like `OwnedInput` in LiquidJS for example? where you have your blinders, asset & value AND the index

**Comment by altafan** [comment]
@tiero done.

**Comment by tiero** [comment]
What abou SwapReuqest?

**Comment by altafan** [comment]
Sorry, done. @tiero

**Pull request merged**
